### ISSUE TITLE
Makefile should allow k8s version to be selected

### ISSUE THREAD

**Issue by ddunlap2005** [advancedtelematic/ota-community-edition#109]
In order to allow the instantiation of the server to be a little more deterministic, you should allow the user to select which Kubernetes is installed through minikube. The following simple patch would allow this:

```
diff --git a/Makefile b/Makefile
index 381a023..71b1213 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,7 @@
 KUBE_VM ?= virtualbox
 KUBE_CPU ?= 2
 KUBE_MEM ?= 8192
+KUBE_VER ?= v1.18.3

 .PHONY: help start clean new-client new-server start-all start-ingress \
   start-infra start-services print-hosts
@@ -10,7 +11,7 @@ help: ## Print this message and exit.
        @awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%20s\033[0m : %s\n", $$1, $$2}' $(MAKEFILE_LIST)

 start: cmd-minikube ## Start minikube and all OTA+ services.
-       @minikube ip 2>/dev/null || minikube start --vm-driver $(KUBE_VM) --cpus $(KUBE_CPU) --memory $(KUBE_MEM)
+       @minikube ip 2>/dev/null || minikube start --vm-driver $(KUBE_VM) --cpus $(KUBE_CPU) --memory $(KUBE_MEM) --kubernetes-version ${KUBE_VER}
        @scripts/start.sh start-all

 clean: cmd-minikube ## Delete minikube and all service data.
```

**Comment by patrickvacek** [comment]
@alexhumphreys what do you think about this?

**Comment by alexhumphreys** [comment]
Aye, seems like a good idea! Just tried it there and had to update my super old version of Minikube, but aside from that I don't think there should be any issues with this change.

**Comment by patrickvacek** [comment]
I do wonder if it makes sense to hardcode a version by default. I think I'd prefer if the current behavior were left as is by default, but having the option to specify a version seems reasonable.

**Comment by alexhumphreys** [comment]
On `minikube` version `v1.13.0` it starts with k8s `v1.19.0` by default, presumably older versions of minikube have older k8s defaults. But we're basically wrapping `minikube start` in this `start` make target, and `minikube start` has like 60+ options, maybe all of which have defaults. We currently allow 3 of them to but configurable (`KUBE_VM`, `KUBE_CPU`, `KUBE_MEM`), I guess because the defaults don't support `ota-community-edition` out of the box? So not sure there's any principled reason for or against adding a 4th one as configurable, anyone doing anything remotely interesting with minikube is probably gonna need to pass a bunch and then this command becomes useless.

That could be an argument for splitting the "start minikube" and "start ota" stuff into different targets, but I'm just riffing here.

**Comment by ddunlap2005** [comment]
For the older ota-community-edition, it was a requirement to use an older Kubernetes Version. The Deployment templates still used `extensions/v1beta1` instead of the modern `apps/v1` which required the older Kubernetes. This particular issue, at least for now, is a non-issue with the latest code.
